from bottomfw.common.flavor_amplitudes import FlavorAmplitudes

test_flavor_amplitudes = FlavorAmplitudes(baryons="omegas")

test_transition_lambda_0_sigma_0_1 = test_flavor_amplitudes.transition_lambda_0_sigma_0_1()
print(test_transition_lambda_0_sigma_0_1)

test_transition_lambda_0_sigma_0_2 = test_flavor_amplitudes.transition_lambda_0_sigma_0_2()
print(test_transition_lambda_0_sigma_0_2)

test_transition_lambda_0_sigma_0_3 = test_flavor_amplitudes.transition_lambda_0_sigma_0_3()
print(test_transition_lambda_0_sigma_0_3)

test_transition_Xi_0_Xi_prime_0_1 = test_flavor_amplitudes.transition_Xi_0_Xi_prime_0_1()
print(test_transition_Xi_0_Xi_prime_0_1)

test_transition_Xi_0_Xi_prime_0_2 = test_flavor_amplitudes.transition_Xi_0_Xi_prime_0_2()
print(test_transition_Xi_0_Xi_prime_0_2)

test_transition_Xi_0_Xi_prime_0_3 = test_flavor_amplitudes.transition_Xi_0_Xi_prime_0_3()
print(test_transition_Xi_0_Xi_prime_0_3)

test_transition_Xi_m_Xi_prime_m_1 = test_flavor_amplitudes.transition_Xi_m_Xi_prime_m_1()
print(test_transition_Xi_m_Xi_prime_m_1)

test_transition_Xi_m_Xi_prime_m_2 = test_flavor_amplitudes.transition_Xi_m_Xi_prime_m_2()
print(test_transition_Xi_m_Xi_prime_m_2)

test_transition_Xi_m_Xi_prime_m_3 = test_flavor_amplitudes.transition_Xi_m_Xi_prime_m_3()
print(test_transition_Xi_m_Xi_prime_m_3)

test_transition_Lambda_0_Lambda_0_1 = test_flavor_amplitudes.transition_Lambda_0_Lambda_0_1()
print(test_transition_Lambda_0_Lambda_0_1)

test_transition_Lambda_0_Lambda_0_2 = test_flavor_amplitudes.transition_Lambda_0_Lambda_0_2()
print(test_transition_Lambda_0_Lambda_0_2)

test_transition_Lambda_0_Lambda_0_3 = test_flavor_amplitudes.transition_Lambda_0_Lambda_0_3()
print(test_transition_Lambda_0_Lambda_0_3)


